name: Pipeline de CI - flag-service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: FIAP-Teach-Challenge-2/toggle-master-ci/.github/workflows/reusable-ci-python.yml@main
    with:
      service-name: flag-service
      ecr-repository: togglemaster/flag-service
      needs-postgres: true
    secrets: inherit
